# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Listing checked out files
        run: ls -lah
        
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: target.txt
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    
    environment: sample-environment
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      
      - name: Listing downloaded files
        run: ls -lahR
        
      - name: CURLing
        run: |
          curl --location --request PUT "https://dfwhpersonal.blob.core.windows.net/\$web/hello-world.txt$azure_storage_sas" \
            --header 'x-ms-blob-type: BlockBlob' \
            --header 'Content-Type: text/plain' \
            --data-raw 'Hello, world!'
  
